---
title: "Optimisation de la prime"
subtitle: "ACT-1000"
author: "J.P. Le Cavalier"
date: "3 décembre 2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [xaringan-themer.css, extra.css]
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
library(knitr)
library(xaringanthemer)
library(ggplot2)
library(patchwork)
library(extrafont)
library(scales)
library(data.table)

set.seed(20211203L)

options(htmltools.dir.version = FALSE)
opts_chunk$set(
  echo = FALSE,
  fig.path = "img/",
  fig.width = 15,
  fig.height = 100/15,
  fig.retina = 3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.showtext = FALSE,
  fig.align = "center",
  hiline = TRUE
)

style_duo(
  primary_color = "#53565A",
  secondary_color = "#FDDB00",
  title_slide_background_image = "logo.svg",
  title_slide_background_size = "320px",
  title_slide_background_position = "10% 90%",
  text_font_google = google_font("Roboto"),
  header_font_google = google_font("Roboto Condensed")
)

theme_set(
  theme_minimal(
    base_size = 12L,
    base_family = gsub("'", '', theme_xaringan_get_value("text_font_family"))
  ) +
    theme(
      text = element_text(
        color = theme_xaringan_get_value("text_color")
      ),
      title = element_text(
        family = gsub("'", '', theme_xaringan_get_value("header_font_family")),
        color = theme_xaringan_get_value("header_color")
      ),
      line = element_line(
        color = lighten_color(theme_xaringan_get_value("background_color"), 0.1)
      ),
      plot.background = element_rect(
        color = NA,
        fill = theme_xaringan_get_value("background_color")
      ),
      plot.margin = margin(10, 10, 10, 10),
      plot.title = element_text(
        size = rel(1.5),
        hjust = 0.5,
        margin = margin(0, 0, 20, 0)
      ),
      strip.text = element_text(
        family = gsub("'", '', theme_xaringan_get_value("header_font_family")),
        color = theme_xaringan_get_value("header_color")
      ),
      axis.text = NULL,
      panel.grid = NULL,
      legend.position = "bottom"
    )
)

update_geom_defaults("text", list(
  family = theme_get()$text$family
))
update_geom_defaults("label", list(
  family = theme_get()$text$family
))
update_geom_defaults("col", list(
  fill = theme_xaringan_get_value("text_bold_color")
))
update_geom_defaults("point", list(
  color = theme_xaringan_get_value("text_color")
))
update_geom_defaults("line", list(
  color = theme_xaringan_get_value("text_color")
))
```

```{r insured}
insured <- data.table(id_insured = 1:6)
insured[, name := paste("Assuré", id_insured)]
insured[, pure_premium := c(763, 520, 778, 824, 723, 964)]
insured[, prob_buy := mapply(
  FUN = function(B, v, Q, M) function(premium) 1 - 1 / (1 + Q * exp(-B * (premium - M))) ^ (1 / v),
  B = c(0.035, 0.04, 0.02, 0.01, 0.02, 0.025),
  v = c(0.5, 0.1, 0.92, 0.37, 0.75, 0.68),
  Q = c(0.5, 0.2, 0.92, 0.45, 0.5, 0.5),
  M = c(763, 473, 800, 840, 672, 982)
)]

data <- insured[, rbindlist(mapply(function(id_insured, pure_premium, prob_buy) {
  
  data.table(
    id_insured = id_insured,
    premium = 0:1600
  )[, `:=`(
    profit = premium - pure_premium,
    prob_buy = prob_buy(premium)
  )][, `:=`(
    exp_profit = prob_buy * profit
  )]
  
}, id_insured = id_insured, pure_premium = pure_premium, prob_buy = prob_buy, SIMPLIFY = FALSE))]

plot_base <- ggplot(data, aes(x = premium)) +
  scale_x_continuous(name = expression(π[i])) +
  facet_wrap(
    facets = vars(id_insured),
    ncol = 2L,
    labeller = as_labeller(insured[, setNames(name, id_insured)])
  )

plot_profit <- plot_base +
  geom_line(aes(y = profit)) +
  scale_y_continuous(name = expression(p[i](π[i]))) +
  coord_cartesian(xlim = c(0, 1500)) +
  labs(title = "Profit")

plot_prob_buy <- plot_base +
  geom_line(aes(y = prob_buy)) +
  scale_y_continuous(name = expression(γ[i](π[i]))) +
  coord_cartesian(xlim = c(0, 1500)) +
  labs(title = "Probabilité d'achat")

plot_exp_profit <- plot_base +
  geom_line(aes(y = exp_profit)) +
  scale_y_continuous(name = expression(tilde(p[i])(π[i])), position = "right") +
  coord_cartesian(xlim = c(0, 1500), ylim = c(-30, 40)) +
  labs(title = "Profit espéré")
```

```{r ptf}
opt_premium <- function(pure_premium, prob_buy, lambda) {
  
  optimize(
    f = function(premium) prob_buy(premium) * (premium - pure_premium) + lambda * prob_buy(premium),
    interval = c(0, 2000),
    maximum = TRUE
  )$maximum
  
}

data_ptf <- insured[, rbindlist(mapply(function(id_insured, pure_premium, prob_buy) {
  
  ptf_mean <- data.table(
    id_ptf = 1L,
    id_insured = id_insured,
    type = "mean",
    ptf_ngdt = TRUE,
    ptf_pp = FALSE,
    ptf_optim = FALSE,
    ptf_random = FALSE,
    lambda = NA_integer_,
    premium = insured[, mean(pure_premium)]
  )
  
  ptf_pp <- data.table(
    id_ptf = 2L,
    id_insured = id_insured,
    type = "pure_premium",
    ptf_ngdt = FALSE,
    ptf_pp = TRUE,
    ptf_optim = FALSE,
    ptf_random = FALSE,
    lambda = NA_integer_,
    premium = pure_premium
  )
  
  ptf_profitability <- data.table(
    id_ptf = 3L,
    id_insured = id_insured,
    type = "profitability",
    ptf_ngdt = FALSE,
    ptf_pp = FALSE,
    ptf_optim = TRUE,
    ptf_random = FALSE,
    lambda = 0,
    premium = opt_premium(pure_premium, prob_buy, 0)
  )
  
  ptf_optim <- data.table(
    id_ptf = 3L + 1:100,
    id_insured = id_insured,
    type = "optimal",
    ptf_ngdt = FALSE,
    ptf_pp = FALSE,
    ptf_optim = TRUE,
    ptf_random = FALSE,
    lambda = 1:100
  )[, `:=`(
    premium = sapply(lambda, opt_premium, pure_premium = pure_premium, prob_buy = prob_buy)
  )]
  
  ptf_growth <- data.table(
    id_ptf = 104L,
    id_insured = id_insured,
    type = "growth",
    ptf_ngdt = FALSE,
    ptf_pp = FALSE,
    ptf_optim = TRUE,
    ptf_random = FALSE,
    lambda = Inf,
    premium = 0
  )
  
  ptf_random <- data.table(
    id_ptf = 105:205,
    id_insured = id_insured,
    type = "random",
    ptf_ngdt = FALSE,
    ptf_pp = FALSE,
    ptf_optim = FALSE,
    ptf_random = TRUE,
    lambda = NA_integer_
  )[, `:=`(
    premium = pure_premium * runif(.N, 0.9, 1.1)
  )]
  
  ptf <- rbindlist(list(ptf_mean, ptf_pp, ptf_profitability, ptf_optim, ptf_growth, ptf_random))
  
  ptf[, `:=`(
    type = factor(type, c("mean", "random", "pure_premium", "profitability", "growth", "optimal")),
    profit = premium - pure_premium,
    prob_buy = prob_buy(premium)
  )][, `:=`(
    exp_profit = prob_buy * profit
  )]
  
  ptf[]
  
}, id_insured = id_insured, pure_premium = pure_premium, prob_buy = prob_buy, SIMPLIFY = FALSE))]
```

## Définitions

---

## Définitions

```{r definition-1}
plot_profit
```

---

## Définitions

---

## Définitions

```{r definition-2}
plot_prob_buy + plot_exp_profit
```

---

## Un modèle de prime moyenne

---

## Un modèle de prime moyenne

```{r model-mean}
scale_mean <- scale_fill_manual(
  name = NULL,
  values = c(
    mean = theme_xaringan_get_value("text_color")
  ),
  labels = c("Prime moyenne")
)

plot_prob_buy_mean <- plot_prob_buy +
  geom_point(
    data = data_ptf[type == "mean"],
    mapping = aes(y = prob_buy, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_mean

plot_exp_profit_mean <- plot_exp_profit +
  geom_point(
    data = data_ptf[type == "mean"],
    mapping = aes(y = exp_profit, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_mean

plot_prob_buy_mean + plot_exp_profit_mean + plot_layout(guides = "collect")
```

---

## Un modèle de segmentation

---

## Un modèle de segmentation

```{r model-pp}
scale_pp <- scale_fill_manual(
  name = NULL,
  values = c(
    mean = theme_xaringan_get_value("text_color"),
    pure_premium = theme_xaringan_get_value("text_bold_color")
  ),
  labels = c("Prime moyenne", "Prime pure")
)

plot_prob_buy_pp <- plot_prob_buy +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium")],
    mapping = aes(y = prob_buy, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_pp

plot_exp_profit_pp <- plot_exp_profit +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium")],
    mapping = aes(y = exp_profit, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_pp

plot_prob_buy_pp + plot_exp_profit_pp + plot_layout(guides = "collect")
```

---

## Un modèle de rentabilité

---

## Un modèle de rentabilité

```{r model-profitability}
scale_profitability <- scale_fill_manual(
  name = NULL,
  values = c(
    mean = theme_xaringan_get_value("text_color"),
    pure_premium = theme_xaringan_get_value("text_bold_color"),
    profitability = "darkgreen"
  ),
  labels = c("Prime moyenne", "Prime pure", "Profit espéré maximum")
)

plot_prob_buy_profitability <- plot_prob_buy +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium", "profitability")],
    mapping = aes(y = prob_buy, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_profitability

plot_exp_profit_profitability <- plot_exp_profit +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium", "profitability")],
    mapping = aes(y = exp_profit, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_profitability

plot_prob_buy_profitability + plot_exp_profit_profitability + plot_layout(guides = "collect")
```

---

## Un modèle de croissance

---

## Un modèle de croissance

```{r model-growth}
scale_growth <- scale_fill_manual(
  name = NULL,
  values = c(
    mean = theme_xaringan_get_value("text_color"),
    pure_premium = theme_xaringan_get_value("text_bold_color"),
    profitability = "darkgreen",
    growth = "darkred"
  ),
  labels = c("Prime moyenne", "Prime pure", "Profit espéré maximal", "Croissance maximale")
)

plot_prob_buy_growth <- plot_prob_buy +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium", "profitability", "growth")],
    mapping = aes(y = prob_buy, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_growth

plot_exp_profit_growth <- plot_exp_profit +
  geom_point(
    data = data_ptf[type %in% c("mean", "pure_premium", "profitability", "growth")],
    mapping = aes(y = exp_profit, fill = type),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  scale_growth

plot_prob_buy_growth + plot_exp_profit_growth + plot_layout(guides = "collect")
```

---

## Un modèle de croissance rentable

---

## Un modèle de croissance rentable

```{r model-profitable-growth}
lambda_show <- seq(0L, 100L, 20L)

scale_lambda <- scale_fill_gradient(
  name = "λ",
  low = "darkgreen",
  high = "lightgreen",
  breaks = lambda_show,
  guide = guide_legend(
    nrow = 1L,
    title.position = "bottom",
    title.hjust = 0.5,
    label.position = "bottom"
  )
)

plot_prob_buy_profitable_growth <- plot_prob_buy +
  geom_point(
    data = data_ptf[lambda %in% lambda_show],
    mapping = aes(y = prob_buy, fill = lambda),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  geom_point(
    data = data_ptf[type == "pure_premium"],
    mapping = aes(y = prob_buy),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color"),
    fill = theme_xaringan_get_value("text_bold_color")
  ) +
  scale_lambda

plot_exp_profit_profitable_growth <- plot_exp_profit +
  geom_point(
    data = data_ptf[lambda %in% lambda_show],
    mapping = aes(y = exp_profit, fill = lambda),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color")
  ) +
  geom_point(
    data = data_ptf[type == "pure_premium"],
    mapping = aes(y = exp_profit),
    shape = 21,
    size = 3,
    color = theme_xaringan_get_value("text_color"),
    fill = theme_xaringan_get_value("text_bold_color")
  ) +
  scale_lambda

plot_prob_buy_profitable_growth + plot_exp_profit_profitable_growth +
  plot_layout(guides = "collect")
```
